config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'omniauth_callbacks'}

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    resources :items
    resources :items_imports
    mount Sidekiq::Web => '/sidekiq'
    get 'pages/home'
    devise_for :users, skip: :omniauth_callbacks
    root to: "people#index"
    resources :people
    get '/search' => 'search#search_people'
    resources :messages
    get 'download_sample_excel' => 'items_imports#download_sample_excel'
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end
end

app/models/person.rb
class Person < ApplicationRecord
#  encrypted_id key: "jhye0e97hjsjsjsjsjsbhtje"
  validates :first_name, :last_name, :email, :age, :gender, presence: true
  validates :email, uniqueness: true
  validates :first_name, :last_name, length: {minimum: 8}

  scope :active_persons_with_long_name, -> { where("LENGTH(first_name) > 6").where(isDeleted: false) }
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    # @people = Person.where("LENGTH(first_name) > 6")
    # @people = Person.where(isDeleted: false)
    @people = Person.active_persons_with_long_name
    @time_ago = helpers.time_ago_in_words(Time.now)
    # HelloWorldJob.set(wait: 25.seconds).perform_later
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @name = helpers.name(@person)
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)
    # byebug

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.isDeleted = true
    @person.save
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def person_params
      params.require(:person).permit(:first_name, :last_name, :email, :age, :gender)
    end
end

app/helpers/people_helper.rb
module PeopleHelper
  def name(person)
    if person.gender.downcase == "m" or person.gender.downcase == "male"
      "Mr." + " " + person.first_name + " " + person.last_name
    else
      "Miss." + " " + person.first_name + " " + person.last_name
    end
  end
end

app/views/people/_form.html.erb
<%= form_with(model: person, local: true) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> <%= t('people.errors.prohibited_this_person') %></h2>

      <ul>
        <% person.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label t('people.first_name') %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label t('people.last_name') %>
    <%= form.text_field :last_name  %>
  </div>

  <div class="field">
    <%= form.label t('people.email') %>
    <%= form.text_field :email  %>
  </div>

  <div class="field">
    <%= form.label t('people.age') %>
    <%= form.number_field :age  %>
  </div>

  <div class="field">
    <%= form.label t('people.gender') %>
    <%= form.text_field :gender  %>
  </div>

  <div class="actions">
    <%= form.submit t('global.forms.submit'), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/people/_people_listing.html.erb
<table class="people_listings">
  <thead>
    <tr>
      <th><%= t('people.people_listing.first_name') %></th>
      <th><%= t('people.people_listing.last_name') %></th>
      <th><%= t('people.people_listing.email') %></th>
      <th><%= t('people.people_listing.age') %></th>
      <th><%= t('people.people_listing.gender') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.first_name %></td>
        <td><%= person.last_name %></td>
        <td><%= person.email %></td>
        <td><%= person.age %></td>
        <td><%= person.gender %></td>
        <td><%= link_to t('global.show'), person, class: "btn btn-primary" %></td>
        <td><%= link_to t('global.edit'), edit_person_path(person), class: "btn btn-primary" %></td>
        <td><%= link_to t('global.destroy'), person, method: :delete, data: { confirm: t('global.are_you_sure') }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/people/edit.html.erb
<div class="container hr">
  <h1><%= t('people.editing_person') %></h1>
  <p></p>
  <%= link_to t('global.show'), @person, class: "btn btn-primary" %> |
  <%= link_to t('global.back'), people_path, class: "btn btn-primary"  %>
  <p></p>
  <%= render 'form', person: @person %>
</div>

app/views/people/index.html.erb
<div class="container hr">
  <div class="people_table">
    <%= render partial: "search/search_form" %>
    <h1><%= t('people.people') %></h1>
    <%= render partial: "people_listing" %>
  </div>
</div>

app/views/people/new.html.erb
<div class="container hr">
  <%= javascript_pack_tag 'people' %>

  <div class="people_new">
    <h1><%= t('people.new_person') %></h1>
    <%= link_to t('global.back'), people_path, class: "btn btn-primary" %>
    <p></p>
    <%= render 'form', person: @person %>
  </div>
</div>

app/views/people/show.html.erb
<div class="container hr">
  <p id="notice"><%= notice %></p>

  <h2><%= t('people.showing_the_details') %> <%= @name %></h2>
  <%= link_to t('global.edit'), edit_person_path(@person), class: "btn btn-primary" %> |
  <%= link_to t('global.back'), people_path, class: "btn btn-primary" %>
  <p></p>
  <p>
    <strong><%= t('people.people_listing.first_name') %>:</strong>
    <%= @person.first_name %>
  </p>

  <p>
    <strong><%= t('people.people_listing.last_name') %>:</strong>
    <%= @person.last_name %>
  </p>

  <p>
    <strong><%= t('people.people_listing.email') %>:</strong>
    <%= @person.email %>
  </p>

  <p>
    <strong><%= t('people.people_listing.age') %>:</strong>
    <%= @person.age %>
  </p>

  <p>
    <strong><%= t('people.people_listing.gender') %>:</strong>
    <%= @person.gender %>
  </p>
</div>