config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'omniauth_callbacks'}

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    resources :items
    resources :items_imports
    mount Sidekiq::Web => '/sidekiq'
    get 'pages/home'
    devise_for :users, skip: :omniauth_callbacks
    root to: "people#index"
    resources :people
    get '/search' => 'search#search_people'
    resources :messages
    get 'download_sample_excel' => 'items_imports#download_sample_excel'
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end
end

app/models/items_import.rb
class ItemsImport
  include ActiveModel::Model
  require 'roo'
  attr_accessor :file

  def initialize(attributes={})
    attributes.each { |name, value| send("#{name}=", value) }
  end

  def persisted?
    false
  end

  def open_spreadsheet
    case File.extname(file.original_filename)
    when ".csv" then Csv.new(file.path, nil, :ignore)
    when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
    when ".xlsx" then Roo::Excelx.new(file.path)
    else raise "Unknown file type: #{file.original_filename}"
    end
  end

  def load_imported_items
    spreadsheet = open_spreadsheet
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).map do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      item = Item.find_by_name(row["name"]) || Item.new
      item.attributes = row.to_hash
      item
    end
  end

  def imported_items
    @imported_items ||= load_imported_items
  end

  def save
    if imported_items.map(&:valid?).all?
      imported_items.each(&:save!)
      true
    else
      imported_items.each_with_index do |item, index|
        item.errors.full_messages.each do |msg|
          errors.add :base, "Row #{index + 6}: #{msg}"
        end
      end
      false
    end
  end
end

app/controllers/items_imports_controller.rb
class ItemsImportsController < ApplicationController

  def new
    @items_import = ItemsImport.new
  end

  def download_sample_excel
    send_file("#{Rails.root}/public/sample_excel.xlsx")
  end

  def create
    @items_import = ItemsImport.new(items_import_params)

    respond_to do |format|
      if @items_import.save
        format.html { redirect_to items_path, notice: 'Items import was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  private
  # Only allow a list of trusted parameters through.
  def items_import_params
    # params.require(:items_import).permit(:file_name, :uploaded_by, :uploaded_at, :status)
    params.fetch(:items_import, {}).permit(:file_name, :uploaded_by, :uploaded_at, :status, :file)
  end
end

app/helpers/items_imports_helper.rb
module ItemsImportsHelper
end

app/views/items_imports/new.html.erb
<div class="container hr">
  <h1><%= t('items_imports.import_items_from_excel') %></h1>

  <p>
    <%= t('items_imports.note_only_spreadsheets') %>
  </p>

  <h3><%= t('items_imports.requirements') %></h3>
  <ul>
    <li><%= t("items_imports.here_you_could") %></li>
    <li><%= t("items_imports.that_way_your_user") %></li>
  </ul>

  <h5><%= t('items_imports.select_file') %></h5>
  <%= form_for @items_import do |f| %>
    <% if @items_import.errors.any? %>
      <%= pluralize(@items_import.errors.count, "error") %> <%= t('items_imports.errors.prevented_us') %>
      <ul>
        <% @items_import.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    <% end %>

    <%= f.file_field :file, required: true %>
    <%= f.submit t("items_import.import_file"), class: "btn btn-primary" %>
    <%= link_to t('items_imports.download_sample_excel'), download_sample_excel_path, class: "btn btn-primary" %>
  <% end %>
</div>