config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'omniauth_callbacks'}

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    resources :items
    resources :items_imports
    mount Sidekiq::Web => '/sidekiq'
    get 'pages/home'
    devise_for :users, skip: :omniauth_callbacks
    root to: "people#index"
    resources :people
    get '/search' => 'search#search_people'
    resources :messages
    get 'download_sample_excel' => 'items_imports#download_sample_excel'
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end
end

app/models/item.rb
class Item < ApplicationRecord
  validates_presence_of :name

  def self.to_csv
    attributes = %w{id name quantity}
    CSV.generate(headers: true) do |csv|
      csv << attributes
      all.find_each do |item|
        csv << attributes.map{ |attr| item.send(attr) }
      end
    end
  end

  def self.to_xlsx
    wb = xlsx_package.workbook

    wb.styles do |style|
      project_heading = style.add_style(b: true, sz: 14)
      heading = style.add_style(b: true)

      wb.add_worksheet(name: "Items") do |sheet|
        # Add a title row
        sheet.add_row ["Inventory Items"], style: project_heading
        # Add the date this was downloaded
        sheet.add_row ["Downloaded at", Time.now.strftime("%b %-d, %Y")]
        # Add a blank row
        sheet.add_row []
        # Create the header row
        sheet.add_row ["ID", "Item Name", "Quantity"], style: heading
        # Create the database reference row
        sheet.add_row ["id", "name", "quantity"], style: heading
        # Create entries for each item
        @items.each do |item|
          sheet.add_row [item.id, item.name, item.quantity]
        end
      end
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
    respond_to do |format|
      format.xlsx {
        response.headers[
          'Content-Disposition'
        ] = "attachment; filename=items_list_#{DateTime.now}.xlsx"
      }
      format.html { render :index }
      format.csv { send_data @items.to_csv, filename: "items_list_#{DateTime.now}.csv"}
      format.pdf do
        pdf = GeneratePdf.new(@items)
        send_data pdf.render, filename: "items_list_#{DateTime.now}.pdf", type: "application/pdf"
      end
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:name, :quantity)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> <%= t("global.prohibited_this_item_from_being_saved") %></h2>

      <ul>
        <% item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label t('items.forms.name') %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label t('items.forms.quantity') %>
    <%= form.number_field :quantity %>
  </div>

  <div class="actions">
    <%= form.submit t('global.forms.submit') %>
  </div>
<% end %>

app/views/items/edit.html.erb
<div class="container hr">
  <h1><%= t('items.editing_item') %></h1>
  <p></p>
  <p></p>
  <%= link_to t('global.show'), @item, class: "btn btn-primary" %> |
  <%= link_to t('global.back'), items_path, class: "btn btn-primary" %>
  <p></p>
  <p></p>

  <%= render 'form', item: @item %>
</div>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container hr">
  <h1><%= t("items.items") %></h1>

  <% if @items.size > 0 %>
    <%= link_to t('items.download_as_excel'), items_path(format: :xlsx), class: "btn btn-primary" %>
    <%= link_to t('items.download_as_csv'), items_path(format: :csv), class: "btn btn-primary" %>
    <%= link_to t('items.download_as_pdf'), items_path(format: :pdf), class: "btn btn-primary" %>
  <% end %>
  <%= link_to t('items.upload_from_excel'), new_items_import_path, class: "btn btn-primary" %>
  <%= link_to t('items.new_item'), new_item_path, class: "btn btn-primary" %>

  <table>
    <thead>
      <tr>
        <th><%= t('items.name') %></th>
        <th><%= t('items.quantity') %></th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @items.each do |item| %>
        <tr>
          <td><%= item.name %></td>
          <td><%= item.quantity %></td>
          <td><%= link_to t('global.show'), item, class: "btn btn-primary" %></td>
          <td><%= link_to t('global.edit'), edit_item_path(item), class: "btn btn-primary" %></td>
          <td><%= link_to t('global.destroy'), item, method: :delete, data: { confirm: t('global.are_you_sure') }, class: "btn btn-danger" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/items/new.html.erb
<div class="container hr">
  <h1><%= t("items.new_item") %></h1>
  <%= link_to t('global.back'), items_path, class: "btn btn-primary" %>
  <p></p>
  <p></p>
  <%= render 'form', item: @item %>
</div>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container hr">
  <%= link_to t('global.edit'), edit_item_path(@item), class: "btn btn-primary" %> |
  <%= link_to t('global.back'), items_path, class: "btn btn-primary" %>
  <p>
    <strong><%= t('items.name') %>:</strong>
    <%= @item.name %>
  </p>

  <p>
    <strong><%= t('items.quantity') %>:</strong>
    <%= @item.quantity %>
  </p>
</div>