config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'omniauth_callbacks'}

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    resources :items
    resources :items_imports
    mount Sidekiq::Web => '/sidekiq'
    get 'pages/home'
    devise_for :users, skip: :omniauth_callbacks
    root to: "people#index"
    resources :people
    get '/search' => 'search#search_people'
    resources :messages
    get 'download_sample_excel' => 'items_imports#download_sample_excel'
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end
end

app/views/layouts/_footer.html.erb
<!--<div class="container footer_hr">
</div>-->

app/views/layouts/_header.html.erb
<div class="container">
  <div style="margin-top: 10px;">
    <% flash.each do |key, value| %>
      <div class="<%= flash_class(key) %>">
        <%= value %>
      </div>
    <% end %>
  </div>
  <div class="header_container">
    <% if current_user %>
      <%= link_to t('header.new_person'), new_person_path, class: "btn btn-primary" %>
      <%= link_to t("header.people_list"), root_path, class: "btn btn-primary" %>
      <%= link_to t("header.items_list"), items_path, class: "btn btn-primary" %>
      <%= link_to t("header.live_messages"), messages_path, class: "btn btn-primary" %>
      <%= link_to t("header.home"), root_path, class: "btn btn-primary" %>
      <%= link_to t("header.sign_out"), destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
    <% else %>
      <%= link_to t("header.sign_in"), new_user_session_path, class: "btn btn-primary" %>
      <%= link_to t("header.sign_up"), new_user_registration_path, class: "btn btn-primary" %>
    <% end %>
    <%= link_to t('header.russian'), root_path(locale: :ru), class: "btn btn-primary" %>
    <%= link_to t('header.english'), root_path(locale: :en), class: "btn btn-primary" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t("header.dxc_first_rails_application") %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
    <%= render "layouts/header" %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>